load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "csv_reader",
  hdrs = ["csv_reader.h"],
  srcs = ["csv_reader.cc"],
  deps = [
    "//src/common:matrix",
  ],
)
